# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flasksimpleapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flasksimpleapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c926360eda8f4a2cae5a091c08a57004 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb8df59670124f5bb3339300da134022 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flasksimpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c926360eda8f4a2cae5a091c08a57004 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flasksimpleapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8ec8f8d02e30477eb3c08818ec3893cf }}
        images: 'flasksimpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c926360eda8f4a2cae5a091c08a57004 }}/mltest:${{ github.sha }}'